simple_blog/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  resources :posts do
    resources :comments
  end

end

simple_blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

simple_blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

simple_blog/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length:{minimum: 3}
  validates :body, presence: true, length:{minimum: 5}
end

simple_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

simple_blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

simple_blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = "about us"
    @content = "Yes we're close"
  end
end

simple_blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)
    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  private def post_params
    params.require(:post).permit(:title,:body)
  end


end

simple_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

simple_blog/app/helpers/comments_helper.rb
module CommentsHelper
end

simple_blog/app/helpers/pages_helper.rb
module PagesHelper
end

simple_blog/app/helpers/posts_helper.rb
module PostsHelper
end

simple_blog/app/views/comments/_comments.html.erb
<br>
<% @post.comments.each do |comment| %>
  <br>
  <div class="container">
  <strong><%= comment.username %></strong>
  <p> <%= comment.body %> </p>
  <%= link_to "delete", [comment.post,comment], method: :delete,
                                    data:{confirm: "are you crazy?" }%>
  </div><br>

<% end %>

simple_blog/app/views/comments/_form.html.erb
<h3> add Comments</h3>
<%= form_for([@post,@post.comments.build]) do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field(:username) %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body) %>
  </p>
  <p>
    <%= f.submit({:class => "btn btn-primary"}) %>
  </p>
<% end %>

simple_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-dark">
      <a class="navbar-brand" href="#">My Blogs</a>
      <ul class="navbar-nav nav">
        <li><%= link_to "home", home_path %></li>
      </ul>
      <ul class="navbar-nav">
       <li><%= link_to "Create Post", new_post_path %></li>
      </ul>
    </nav>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

simple_blog/app/views/pages/about.html.erb
<h1> <%= @title %> </h1>
<p> <%= @content %> </p>

simple_blog/app/views/pages/new.html.erb
<h1>new post</h1>

simple_blog/app/views/posts/edit.html.erb
<h1>edit post</h1>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => "form-control"}) %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => "form-control"}) %>
  </p>
  <p>
    <%= f.submit({:class => "btn btn-primary"}) %>
  </p>
<% end %>

simple_blog/app/views/posts/index.html.erb
<% @post.each do |post| %>
  <div class="well">
    <h3> <%= post.title %> </h3 >
    <p> <%= post.body %> </p>
    <%= link_to "read more", post_path(post), :class => 'btn btn-success' %>
  </div>

<% end %>

simple_blog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |e| %>
      <div class="alert alert-danger"><%= e %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => "form-control"}) %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => "form-control"}) %>
  </p>
  <p>
    <%= f.submit({:class => "btn btn-primary"}) %>
  </p>
<% end %>

simple_blog/app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<p> <%= @post.body %> </p>
<hr>
<%= link_to "edit", edit_post_path(@post), :class => 'btn btn-info' %>
<%= link_to "delete", post_path(@post), method: :delete,
                                        data:{confirm: "are you crazy?" },
                                        :class => 'btn btn-danger' %>
<%= render 'comments/comments' %>
<hr>
<%= render 'comments/form' %>